library(gNanoPkg)

#debug(runSim)

data.df = readData()
simPath = here("systematic")

runSim(y~1, data = data.df, simPath = simPath, simRoot = "g-1")
runSim(y~profile + ZST, data = data.df, simPath = simPath, simRoot = "g-2")
runSim(y~profile + locus + ZST, data = data.df, simPath = simPath, simRoot = "g-3")
runSim(y~profile + locus + dye + X + ZST, data = data.df, simPath = simPath, simRoot = "g-4")
runSim(y~profile + locus + dye + X + V + ZST, data = data.df, simPath = simPath, simRoot = "g-5")
runSim(y~profile + locus + dye + locus.dye + X + ZST, data = data.df, simPath = simPath, simRoot = "g-6")
runSim(y~profile + locus + dye + locus.dye + X + V + ZST, data = data.df, simPath = simPath, simRoot = "g-7")

runSim(y~1, data = data.df, simPath = simPath, simRoot = "ln-1", responseDist = "normal")
runSim(y~profile + ZST, data = data.df, simPath = simPath, simRoot = "ln-2", responseDist = "normal")
runSim(y~profile + locus + ZST, data = data.df, simPath = simPath, simRoot = "ln-3", responseDist = "normal")
runSim(y~profile + locus + dye + X + ZST, data = data.df, simPath = simPath, simRoot = "ln-4", responseDist = "normal")
runSim(y~profile + locus + dye + X + V + ZST, data = data.df, simPath = simPath, simRoot = "ln-5", responseDist = "normal")
runSim(y~profile + locus + dye + locus.dye + X + ZST, data = data.df, simPath = simPath, simRoot = "ln-6", responseDist = "normal")
runSim(y~profile + locus + dye + locus.dye + X + V + ZST, data = data.df, simPath = simPath, simRoot = "ln-7", responseDist = "normal")

runSim(y~1, data = data.df, simPath = simPath, simRoot = "sn-1", responseDist = "sn")
runSim(y~profile + ZST, data = data.df, simPath = simPath, simRoot = "sn-2", responseDist = "sn")
runSim(y~profile + locus + ZST, data = data.df, simPath = simPath, simRoot = "sn-3", responseDist = "sn")
runSim(y~profile + locus + dye + X + ZST, data = data.df, simPath = simPath, simRoot = "sn-4", responseDist = "sn")
runSim(y~profile + locus + dye + X + V + ZST, data = data.df, simPath = simPath, simRoot = "sn-5", responseDist = "sn")
runSim(y~profile + locus + dye + locus.dye + X + ZST, data = data.df, simPath = simPath, simRoot = "sn-6", responseDist = "sn")
runSim(y~profile + locus + dye + locus.dye + X + V + ZST, data = data.df, simPath = simPath, simRoot = "sn-7", responseDist = "sn")